# .github/workflows/deploy-frontend.yml
name: Build and deploy Angular app to Azure Web App - carRentalFrontend

on:
  push:
    branches:
      - final_2.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./Angular

      # Step 4: Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: ./Angular

      # Step 5: Upload build artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: ./Angular/dist/reatacar-angular

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 6: Download build artifacts
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      # Step 7: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 8: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'carRentalFrontend'
          package: './Angular/dist/reatacar-angular'
