# .github/workflows/deploy-backend.yml
name: Build and deploy Spring Boot app to Azure Web App - carRentalBackend

on:
  push:
    branches:
      - final_2.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Java environment
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Upload build artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 5: Download build artifacts
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Step 6: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 7: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'carRentalBackend'
          package: '*.jar'
